version: '3.8'

services:
  bot:
    build:
      context: ./bot
      dockerfile: ../Dockerfile
    env_file: ./bot/.env
    network_mode: host
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "until nc -z 127.0.0.1 25565; do echo '⏳ Esperando servidor...'; sleep 2; done; echo '✅ Servidor listo. Iniciando bot...'; npm start"]

volumes:
  mc_clean_data:
